spring:
  application:
    name: backend-library-management-system
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:library
    username: sa
    password:
  h2:
    console:
      enabled: true
